[versions]
alchemist = "36.0.1"
kotlin = "2.1.0"
scalapy = "0.5.3+2-d2eb0088"

[libraries]
alchemist = { module = "it.unibo.alchemist:alchemist", version.ref = "alchemist" }
alchemist-scafi = { module = "it.unibo.alchemist:alchemist-incarnation-scafi", version.ref = "alchemist" }
alchemist-swing = { module = "it.unibo.alchemist:alchemist-swingui", version.ref = "alchemist" }
alchemist-ui-tooling = { module = "it.unibo.alchemist:alchemist-ui-tooling", version.ref = "alchemist" }
alchemist-euclidean-geometry = {module = "it.unibo.alchemist:alchemist-euclidean-geometry", version.ref = "alchemist" }
scalapy = { module = "dev.scalapy:scalapy-core_2.13", version.ref = "scalapy" }

[bundles]
alchemist = [ "alchemist", "alchemist-scafi", "alchemist-euclidean-geometry", "alchemist-swing", "alchemist-ui-tooling"]

[plugins]
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "3.1.7" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = { id = "org.danilopianini.gradle-kotlin-qa", version = "0.74.0" }
multiJvmTesting = { id = "org.danilopianini.multi-jvm-test-plugin", version = "1.3.2" }
taskTree = { id = "com.dorongold.task-tree", version = "4.0.0" }
